language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cecnic1989/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cecnic1989/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'cecnic1989-docker-reach'
  env: 'Cecnic1989DockerReach-env'
  bucket_name: 'elasticbeanstalk-us-east-1-279190937123'
  bucket_path: 'cecnic1989-docker-reach'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
