language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cecnic1989/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cecnic1989/docker-react npm run test
